ASPNET MVC/MVC_Sheet_Tutorial/Controllers/TryExampleController.cs
using Microsoft.Ajax.Utilities;
using MVC_Sheet_Tutorial.Models;
using MVC_Sheet_Tutorial.Models.Context;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
namespace MVC_Sheet_Tutorial.Controllers
{
    public class TryExampleController : Controller
    {
        // GET: TryExample
        // HTML Encoding and Decoding
        public ActionResult Index()
        {
            return View();
        }

        // Question: Set Hidden field value before submitting form using jquery
        // GET: TryExample/SetHiddenField
        [HttpGet]
        public ActionResult SetHiddenField()
        {
            return View();
        }

        // POST: TryExample/SetHiddenField
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SetHiddenField(string name, string role)
        {
            return View("DisplayHiddenField", (name, role));
        }

        // Ajax with JSON // assigning the c# value to js variable.
        // GET: TryExample/ShowPage
        [HttpGet]
        public ActionResult ShowPage()
        {
            List<Student> students = new MVCApplication().Students.ToList();
            StudentExtend st = new StudentExtend() { students = students };
            return View(st);
        }

        // These method can be called with Ajax
        // POST: TryExample/CreateStudent
        [HttpPost]
        public JsonResult CreateStudent(Student stud)
        {
            if (ModelState.IsValid)
            {
                MVCApplication db = new MVCApplication();
                db.Students.Add(stud);
                db.SaveChanges();
                return Json(new { message = "Success", student = new { name = stud.Name, address = stud.Address, standard = stud.Standard, city = stud.City } }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { message = "Error" }, JsonRequestBehavior.AllowGet);

        }

        // To serve the files to the user from the App_Data folder.
        // GET: TryExample/GetFile
        public FileResult GetFile()
        {
            return File("~/App_Data/Images/download.jpg", "image/jpg");
        }


        // GET: TryExample/ThrowError
        [HandleError(View = "Error", ExceptionType = typeof(ApplicationException))]  // Handle Error attribute and passing the View name of the error there are several parameter properties available
        public ActionResult ThrowError()
        {
            int no = Convert.ToInt32("Prath");   // these code line will throw an error.
            return Content("These is the error view ");
        }

        // GET: TryExample/ErrorPage
        public ActionResult ErrorPage()
        {
            return View("Error");
        }

        // GET: TryExample/Cookie
        public ActionResult CookieT()
        {
            // Setting the Cookie
            HttpCookie cookie = new HttpCookie("PrathamApp");
            cookie.Value = "Hello Dear these is the cookie";
            cookie["apikey"] = "dfdsafa"; // appends the cookie using &key=value
            Response.AppendCookie(cookie);
            return View();
        }

        // GET: TryExample/SessionGEt
        public ActionResult SessionGet()
        {
            Session["AppPrathamesh"] = "These is the Prathamesh"; // setting the data in the session.
            return View();
        }

        // GET: TryExample/GetViewNameController
        public ActionResult GetViewNameController()
        {
            ViewBag.ControllerName = this.ControllerContext.RouteData.GetRequiredString("controller");
            return View();
        }

        // get the data using Request.Form 
        // GET: TryExample/FromDataMultiple
        public ActionResult FromDataMultiple()
        {
            return View();
        }

        // POST: TryExample/FromDataMultiple
        [HttpPost]
        [ActionName("FromDataMultiple")]
        public ActionResult PostFormData()
        {
            return View("PostFormData");
        }


        // get the formfield of using Query string by making the formmethod as get.
        // GET: TryExample/QueryStringForm
        public ActionResult QueryStringForm(string firstname)
        {
            if (!String.IsNullOrWhiteSpace(firstname))
            {
                return View("QueryStringData");

            }
            return View();
        }

        // Async Action method
        // GET: TryExample/AsyncView
        public async Task<ActionResult> AsyncView()
        {
            Stopwatch stopwatch = Stopwatch.StartNew();
            List<Product> prods = await GetProducts();
            stopwatch.Stop();
            var data = stopwatch.Elapsed;
            return View(new Tuple<TimeSpan, IEnumerable<Product>>(data, prods.AsEnumerable()));
        }

        // Sync Action method
        // GET: TryExample/SyncView
        public ActionResult syncView()
        {
            Stopwatch stopwatch = Stopwatch.StartNew();
            List<Product> prods = new MVCApplication().Products.ToList();
            stopwatch.Stop();
            var data = stopwatch.Elapsed;
            return View("AsyncView", new Tuple<TimeSpan, IEnumerable<Product>>(data, prods));
        }

        [NonAction]
        public Task<List<Product>> GetProducts()
        {
            MVCApplication db = new MVCApplication();
            return Task.FromResult(db.Products.ToList());
        }

        // GET: TryExample/GetDateView
        // DAtetime formats
        public ActionResult GetDateView()
        {
            return View();
        }

        // Question: Remove records present in List B from List A
        // GET: TryExample/RemoveRecords
        public ActionResult RemoveRecords()
        {
            List<Employee> listA = new List<Employee>
        {
            new Employee { Id = 1, Name = "John Doe", Department = "HR", Address = "123 Street A", Salary = 5000 },
            new Employee { Id = 2, Name = "Jane Smith", Department = "IT", Address = "456 Street B", Salary = 6000 },
            new Employee { Id = 3, Name = "Alice Johnson", Department = "Finance", Address = "789 Street C", Salary = 7000 },
            new Employee { Id = 4, Name = "Bob Williams", Department = "Marketing", Address = "101 Street D", Salary = 4500 },
            new Employee { Id = 5, Name = "Charlie Brown", Department = "IT", Address = "202 Street E", Salary = 6500 }
        };

            // List B with 2 records (same as 2 records from listA)
            List<Employee> listB = new List<Employee>
        {
            new Employee { Id = 2, Name = "Jane Smith", Department = "IT", Address = "456 Street B", Salary = 6000 },
            new Employee { Id = 5, Name = "Charlie Brown", Department = "IT", Address = "202 Street E", Salary = 6500 }
        };

            var removed = listA.Except(listB, new CompareId());
            var intersept = listA.Intersect(listB, new CompareId());
            ICollection<Employee> listacopy = new List<Employee>();
            listA.CopyItemsTo(toSet: listacopy);
            listA.RemoveAll(x => listB.Any(y => y.Id == x.Id));

            // remove duplicate records
            List<Employee> listc = new List<Employee>
        {
            new Employee { Id = 2, Name = "Jane Smith", Department = "IT", Address = "456 Street B", Salary = 6000 },
            new Employee { Id = 5, Name = "Charlie Brown", Department = "IT", Address = "202 Street E", Salary = 6500 },
             new Employee { Id = 5, Name = "Charlie Brown", Department = "IT", Address = "202 Street E", Salary = 6500 },
             new Employee { Id = 2, Name = "Jane Smith", Department = "IT", Address = "456 Street B", Salary = 6000 }
        };

            var dup = listc.GroupBy(emp => new { emp.Id, emp.Name, emp.Salary, emp.Department, emp.Address }).Select(g => g.First());

            return Json(new { lista = listacopy, listb = listB, removed = removed, inter = intersept, listaremoved = listA, duplicate = dup }, JsonRequestBehavior.AllowGet);
        }


        // Trying the custom html helpers like unorderd list
        // GET: Tryexample/CustomHelpers
        public ActionResult CustomHelpers()
        {
            return View();
        }

        public ActionResult MultipleCheckBoxes()
        {
            return View();
        }




    }

    class CompareId : IEqualityComparer<Employee>
    {
        public bool Equals(Employee x, Employee y)
        {
            return x.Id == y.Id;
        }

        public int GetHashCode(Employee obj)
        {
            return obj.Id.GetHashCode();
        }
    }

    class CompareEmployee : IEqualityComparer<Employee>
    {
        public bool Equals(Employee x, Employee y)
        {
            return (x.Id == y.Id && x.Name == y.Name && x.Department == y.Department && x.Address == y.Address && x.Salary == y.Salary);
        }

        public int GetHashCode(Employee obj)
        {
            return obj.GetHashCode();
        }
    }
}

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/AsyncView.cshtml
@model Tuple<TimeSpan, IEnumerable<Product>>
@{
    ViewBag.Title = "AsyncView";
}

<h2>AsyncView</h2>

<p>Time Taken - > @Model.Item1</p>

@foreach (var prod in Model.Item2)
{
    <p>@prod.ProductSellerName</p>
}

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/CookieT.cshtml
@{
    ViewBag.Title = "CookieT";
}

<h2>CookieT</h2>


<h3>Cookie Tutorial</h3>

@Response.Cookies["PrathamApp"].Value

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/CustomHelpers.cshtml
@using MVC_Sheet_Tutorial.CustomHelper

@{
    ViewBag.Title = "CustomHelpers";
}

<h2>CustomHelpers</h2>

<h6>Unordered List</h6>
@Html.CreateList(ListHtml.UL, new List<string> { "Prathamesh", "John", "Livon", "Acer" })


<h6>Ordered List</h6>
@Html.CreateList(ListHtml.OL, new List<string> { "Prathamesh", "John", "Livon", "Acer" })

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/DisplayHiddenField.cshtml
@model (string, string)
@{
    ViewBag.Title = "DisplayHiddenField";
}

<h2>DisplayHiddenField</h2>

<p> Displaying the Hidden Field</p>

@Html.DisplayFor(e => e.Item1)
@Html.DisplayFor(e => e.Item2)

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/FromDataMultiple.cshtml
@model MVC_Sheet_Tutorial.Models.Product

@{
    ViewBag.Title = "FromDataMultiple";
    FormMethod method = FormMethod.Post;
}


<h2>FromDataMultiple</h2>


@using (Html.BeginForm("FromDataMultiple", "TryExample", method))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductSellerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductSellerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductSellerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductAddedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductAddedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductAddedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductWarrantyYears, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductWarrantyYears, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductWarrantyYears, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Post Request" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    
}

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/GetDateView.cshtml
@{
    ViewBag.Title = "GetDateView";
    DateTime dt = DateTime.Now;
}

<h2>GetDateView</h2>

<p>@dt.ToString("dd - MM - yyyy hh:mm:ss tt")</p>

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/GetViewNameController.cshtml
@{
    ViewBag.Title = "GetViewNameController";
}

<h2>GetViewNameController</h2>

<h6>Controller Name using Model -> @ViewBag.ControllerName</h6>

<p> to Get the Current Action method name and Controller Name</p>

<h6>Action Method Name : -> @ViewContext.RouteData.Values["action"].ToString()</h6>
<h6>Controller Class Name : -> @ViewContext.RouteData.Values["controller"].ToString()</h6>

<p>Keys present in RouteData Property</p>
@foreach (var values in ViewContext.RouteData.Values)
{
    <span>@values.Key -> @values.Value</span>
    <br />
}

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/Index.cshtml
@model string
@{
    ViewBag.Title = "Index";
    string comment = "<script>alert('site is hacked')</script>";
    Page.Title = "Setted using Page Property";
}

<h2>Index</h2>

<p>Value from .Config file</p>
<div class="p-3 text-bg-success">@System.Configuration.ConfigurationManager.AppSettings["databaseName"].ToString()</div>

@*Rendering the action method directly in the Razor view*@
@{Html.RenderAction("SetHiddenField");}

<h2>Trying the Example and seeing what are their result</h2>

@*Encoding and decoding examples*@
@Html.Encode("<b>Prathamesh </b>")
@Html.Raw("<b>Prathamesh</b>")

<!--Handling the comment automatically-->
<p>HTML Encoding - > @comment</p>
@Html.Raw(comment)

<img src="~/Content/Images/download.jpg" />

@RenderPage("~/Views/Home/About.cshtml")

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/PostFormData.cshtml
@{
    ViewBag.Title = "PostFormData";
}

<h2>PostFormData</h2>

<h4>using Request.Form</h4>
@foreach (var keys in Request.Form.AllKeys)
{
    <p>@keys -> @Request.Form[keys]</p>
}

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/QueryStringData.cshtml
@{
    ViewBag.Title = "QueryStringData";
}

<h2>QueryStringData</h2>


<h4>Using QueryString</h4>
@foreach (var key in Request.QueryString.AllKeys)
{
    <p>@key -> @Request.QueryString[key] </p>
}

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/QueryStringForm.cshtml
@model MVC_Sheet_Tutorial.Models.User

@{
    ViewBag.Title = "QueryStringForm";
}

<h2>QueryStringForm</h2>


@using (Html.BeginForm("QueryStringForm", "TryExample", FormMethod.Get))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="GET Request" class="btn btn-success" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/SessionGet.cshtml
@{
    ViewBag.Title = "SessionGet";
}

<h2>SessionGet</h2>

<p>Retrieving the Session</p>
@Session["AppPrathamesh"]

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/SetHiddenField.cshtml
@{
    ViewBag.Title = "SetHiddenField";
}

<h2>SetHiddenField</h2>

@{ Html.BeginForm();}
@Html.AntiForgeryToken()
@Html.Hidden("role", "Admin", new { id = "rolefield" })
<p>Here the Hidden field is Role with Value as Admin</p>
@Html.Label("name", "Enter Your Name")
@Html.TextBox("name", "Prathamesh", new { @class = "form-control " })
<br />
<button type="submit" value="submit" class="btn btn-info">Submit</button>
@{ Html.EndForm();}

@section scripts{

    <script>
        //Changing the value of the hidden field before submitting the form
        $("form").on("submit", function () {
            $("#rolefield").val("User")

        })
    </script>
}

ASPNET MVC/MVC_Sheet_Tutorial/Views/TryExample/ShowPage.cshtml
@model StudentExtend
@using MVC_Sheet_Tutorial.Models
@{

    ViewBag.Title = "ShowPage";
}

<h2>ShowPage</h2>

@{
    string username = "MVC Sharp Tutorial";
}

<h5 class="text-decoration-underline text-bg-dark p-3">Create Student</h5>

@using (Html.BeginForm("ShowPage", "TryExampleController", FormMethod.Post, htmlAttributes: new { id = "student-form", @class = "d-flex gap-3" }))
{
    <div class="form-group">
        @Html.LabelFor(model=>model.Name)
        @Html.TextBoxFor(model => model.Name, new { id = "namebox", @class = "box", name = "name" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.City)
        @Html.TextBoxFor(model => model.City, new { id = "citybox", @class = "box", name = "city" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Address)
        @Html.TextBoxFor(model => model.Address, new { id = "addrbox", @class = "box", name = "address" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Standard)
        @Html.TextBoxFor(model => model.Standard, new { id = "stdbox", @class = "box", @type = "number", name = "standard" })
    </div>
    <button value="submit" type="submit" class="btn btn-success" id="create-student">Create</button>

}

<h5 class="text-decoration-underline text-bg-dark p-3 mt-5">List Student</h5>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Standard)
        </th>

    </tr>
    <tbody class="table-body">


        @foreach (var item in Model.students)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Standard)
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script>
        $("#student-form").on("submit", function (e) {
            e.preventDefault();

        })

        // ajax with json data
        $("#create-student").click(function () {
            let postData = { name: $("#namebox").val(), standard: $("#stdbox").val(), city: $("#citybox").val(), address: $("#addrbox").val() }

            // get the data using single without writing the object
            console.log($("#student-form").serialize()) // returns the data in key=value&key=value
            $.ajax({
                url: "/TryExample/CreateStudent",
                method: "POST",
                data: $("#student-form").serialize(),
                success: function (data) {
                    if (data?.message == "Error") {
                        alert("Fill the Fields Properly")
                    }
                    else {
                        createTableRow(data)
                    }
                },

            })
        })




        function createTableRow(student) {
            if (student) {
                student = student?.student
                var tableRow = $("<tr>")
                var tableBody = $(".table-body")
                tableRow.append($("<td>").html(student.name))
                tableRow.append($("<td>").html(student.city))
                tableRow.append($("<td>").html(student.address))
                tableRow.append($("<td>").html(student.standard))
                tableBody.append(tableRow)
                $(".box").val("")
            }
        }

        var value ="@username" // using the C# variable in js
        console.log(value)


    </script>
}