ASPNET MVC/MVC_Sheet_Tutorial/Models/PagingViewModel.cs
using System;
using System.Collections.Generic;

namespace MVC_Sheet_Tutorial.Models
{
    public class PagingViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public int PageCount => (int)Math.Ceiling((double)TotalProducts / PageSize);
        public int TotalProducts { get; set; }
        public int PageNumber { get; set; }
        public int PageSize { get; set; }

    }
}

ASPNET MVC/MVC_Sheet_Tutorial/Models/Product.cs
namespace MVC_Sheet_Tutorial.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ProductMetaData))]
    public partial class Product
    {
        public int ProductId { get; set; }

        public string ProductSellerName { get; set; }

        public decimal ProductPrice { get; set; }

        public int ProductQuantity { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime ProductAddedDate { get; set; }

        public string ProductDescription { get; set; }

        public int ProductWarrantyYears { get; set; }
    }

    public class ProductMetaData
    {
        [Required(ErrorMessage = "product Seller name is required")]
        public string ProductSellerName { get; set; }

        [Required]
        public string ProductDescription { get; set; }
    }

    public class ProductExtend : Product
    {
        [Required(ErrorMessage ="user Type is required")]
        public string UserType { get; set; }
    }
}

ASPNET MVC/MVC_Sheet_Tutorial/Controllers/PagingController.cs
using System.Web.Mvc;
using MVC_Sheet_Tutorial.Models.Context;
using MVC_Sheet_Tutorial.Models;
using System.Linq;
using System.Collections.Generic;
using System;

namespace MVC_Sheet_Tutorial.Controllers
{
    public class PagingController : Controller
    {

        private List<Product> GetProducts(int pageno, out int totalproducts)
        {
            MVCApplication db = new MVCApplication();
            int pageSize = 5;
            pageno = pageno == 0 ? pageno : pageno - 1;
            List<Product> products = db.Products.ToList();
            totalproducts = products.Count;
            return products.OrderBy(pr => pr.ProductId).Skip(pageSize * pageno).Take(pageSize).ToList();
        }

        // GET: Paging
        [HttpGet]
        [Route("Paging/Products/{pageno:int=0}")]
        public ActionResult Products(int pageno)
        {
            int totalProducts = 0;
            List<Product> products = GetProducts(pageno, out totalProducts);
            return View(new PagingViewModel() { Products = products, TotalProducts = totalProducts, PageNumber = pageno, PageSize = 5 });
        }

        // POST: Paging
        [HttpPost]
        [ActionName(nameof(Products))]
        public ActionResult Pagination_Post(int pageno)
        {
            return View();
        }
    }
}

ASPNET MVC/MVC_Sheet_Tutorial/Views/Paging/Products.cshtml
@model MVC_Sheet_Tutorial.Models.PagingViewModel

@{
    ViewBag.Title = "Products Table";
}

<h2>Product Tables</h2>

@{ Html.RenderPartial("_ProductList", Model.Products);}
@if (Model.Products.Count() != 0)
{
    <div class="d-flex justify-content-center align-content-center gap-3">

        @Html.ActionLink("Prev", "Products", "Paging", new { pageno = (Model.PageNumber > 1) ? Model.PageNumber - 1 : 1 }, new { @class = "btn btn-success btn-page" })

        <div class="d-flex justify-content-center align-content-center gap-1">

            @for (int i = 0; i < Model.PageCount; i++)
            {
                @Html.ActionLink((i + 1).ToString(), "Products", "Paging", new { pageno = (i + 1) }, new { @class = Model.PageNumber == (i + 1) ? "btn btn-dark" : "btn btn-outline-dark" })
            }
        </div>

        @Html.ActionLink("Next", "Products", "Paging", new { pageno = Model.PageNumber == Model.PageCount ? Model.PageNumber : Model.PageNumber + 1 }, new { @class = "btn btn-success btn-page" })

    </div>
}